packages:
  - packages/*
  - packages/adapters/*
  - packages/plugins/*
  - packages/plugins/examples/*
  - server
  - ui
  - cli

onlyBuiltDependencies:
  - "@embedded-postgres/darwin-arm64"
  - esbuild
  - node-pty
